package gui;

import sql.Connector;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import util.MesDial;

/**
 * The Frame for creating a new user and updating an existing one
 *
 * @author Alex Hughes <alexhughes117@gmail.com>
 */
public class UserFrame extends GUI {
    
    /**
     * Constructor for UserFrame. If anID == null, then we are talking about a
     * new user. Otherwise, we are talking for an existing one
     *
     * @param aPreviousFrame
     * @param aConnector
     * @param anID
     */
    public UserFrame(GUI aPreviousFrame, Connector aConnector, int anID) {
        super(aPreviousFrame, aConnector, anID);

        initComponents();
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                shutdown();
            }
        });
        if (existing) {
            try {
                loadUser();
            } catch (SQLException ex) {
                MesDial.conError(this);
                Logger.getLogger(UserFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        super.setFrameLocationCenter();
        this.setVisible(true);
    }

    private void loadUser() throws SQLException {
        
    }
    
    private void saveUser() throws SQLException {
        
    }
    
    public static boolean isInstanceAlive() {
        return instanceAlive;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
