SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP SCHEMA IF EXISTS `mpakaloteftero` ;
CREATE SCHEMA IF NOT EXISTS `mpakaloteftero` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mpakaloteftero` ;

-- -----------------------------------------------------
-- Table `expense`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expense` ;

CREATE  TABLE IF NOT EXISTS `expense` (
  `expenseID` BIGINT NOT NULL ,
  `Name` VARCHAR(45) NOT NULL ,
  `Description` TEXT NULL ,
  `Price` DECIMAL(18,2) NULL ,
  `Paid` TINYINT NOT NULL DEFAULT 0 ,
  `DateCreated` TIMESTAMP NULL ,
  `_dateModified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,
  PRIMARY KEY (`expenseID`) )
ENGINE = InnoDB;

USE `mpakaloteftero` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
